# Generated by Django 5.1 on 2024-08-24 14:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('court_name', models.CharField(max_length=100)),
                ('court_type', models.CharField(max_length=100)),
                ('court_surface', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_slot', models.IntegerField(choices=[(9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00')], validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(18)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.courts')),
            ],
            options={
                'unique_together': {('court', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'booking_date')},
            },
        ),
    ]
