# Generated by Django 5.1 on 2024-08-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='image_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
